In [1]:
import pandas as pd
from pathlib import Path

C:\Users\swapn\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\swapn\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [3]:
PROJECT_ROOT = Path(r"C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england")
RAW_PATH = PROJECT_ROOT / "data" / "raw"

In [5]:
LA_CODE = "E06000047"

epc_postcode = pd.read_csv(RAW_PATH / f"postcode_risk_final_{LA_CODE}.csv")
epc_postcode.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High

In [7]:
list(RAW_PATH.glob("*.csv"))

[WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/epc_clean_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/epc_full_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/epc_latest_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/epc_latest_engineered_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/epc_sample_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/postcode_risk_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/postcode_risk_final_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/postcode_risk_scored_E06000047.csv'),
 WindowsPath('C:/Users/swapn/OneDrive/Desktop/fuel_poverty_risk_england/data/raw/summary_E06000047.csv')]

In [9]:
fuel_poverty = pd.read_excel(RAW_PATH / "fuel_poverty_la_2023.xlsx")
fuel_poverty.head()

          Sub-regional Fuel Poverty in England, 2023
0  This spreadsheet contains data tables related ...
1  Fuel poverty in England is measured using the ...
2  Household numbers have been applied at sub-reg...
3                                                NaN
4                                  Publication Dates

In [11]:
xls = pd.ExcelFile(RAW_PATH / "fuel_poverty_la_2023.xlsx")
print(xls.sheet_names)

['Title', 'Contents', 'Metadata', 'Notes', 'Table 1', 'Table 2', 'Table 3', 'Table 4']

In [13]:
fp_test = pd.read_excel(RAW_PATH / "fuel_poverty_la_2023.xlsx", sheet_name="Table 1")
fp_test.head(15)

,"Table 1: Fuel Poverty in England by Region, 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,NaN,NaN
1,Region,Number of households,Number of households in fuel poverty,Proportion of households fuel poor (%)
2,North East,1217443,129082,10.6
3,North West,3248748,393065,12.1
4,Yorkshire and The Humber,2420220,354972,14.67
5,East Midlands,2142036,250162,11.68
6,West Midlands,2464883,411969,16.71
7,East,2733059,263859,9.65
8,London,3714857,345864,9.31
9,South East,4022346,388073,9.65
10,South West,2604780,264601,10.16
11,All households,24568372,2801647,11.4
12,NaN,NaN,NaN,England
13,NaN,NaN,NaN,NaN
14,Back to contents,NaN,NaN,NaN

In [15]:
fp_la_test = pd.read_excel(
    RAW_PATH / "fuel_poverty_la_2023.xlsx",
    sheet_name="Table 2"
)
fp_la_test.head(15)

,"Table 2: Fuel poor households in England by Local Authority, 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Local Authority code,Nation or Region,County or Unitary Authority,Local Authority District,Number of households,Number of households in fuel poverty,Proportion of households fuel poor (%)
2,E92000001,ENGLAND,NaN,NaN,24568372,2801647,11.4
3,E12000001,NORTH EAST,NaN,NaN,1217443,129082,10.6
4,E06000047,NORTH EAST,County Durham,NaN,242909,27698,11.4
5,E06000005,NORTH EAST,Darlington,NaN,50630,5482,10.83
6,E06000001,NORTH EAST,Hartlepool,NaN,42412,4496,10.6
7,E06000002,NORTH EAST,Middlesbrough,NaN,62381,7438,11.92
8,E06000057,NORTH EAST,Northumberland,NaN,152099,16198,10.65
9,E06000003,NORTH EAST,Redcar and Cleveland,NaN,63861,6977,10.93
10,E06000004,NORTH EAST,Stockton-on-Tees,NaN,86776,7978,9.19
11,E11000007,NORTH EAST,Tyne and Wear (Met County),NaN,516375,52815,10.23
12,E08000037,NORTH EAST,Tyne and Wear (Met County),Gateshead,92260,9263,10.04
13,E08000021,NORTH EAST,Tyne and Wear (Met County),Newcastle upon Tyne,127149,14044,11.05
14,E08000022,NORTH EAST,Tyne and Wear (Met County),North Tyneside,99585,8467,8.5

In [20]:
fuel_poverty_la = pd.read_excel(
    RAW_PATH / "fuel_poverty_la_2023.xlsx",
    sheet_name="Table 2",
    header=1
)

fuel_poverty_la.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Local Authority code,Nation or Region,County or Unitary Authority,Local Authority District,Number of households,Number of households in fuel poverty,Proportion of households fuel poor (%)
1,E92000001,ENGLAND,NaN,NaN,24568372,2801647,11.4
2,E12000001,NORTH EAST,NaN,NaN,1217443,129082,10.6
3,E06000047,NORTH EAST,County Durham,NaN,242909,27698,11.4
4,E06000005,NORTH EAST,Darlington,NaN,50630,5482,10.83

In [22]:
fuel_poverty_la.columns = fuel_poverty_la.iloc[0]
fuel_poverty_la = fuel_poverty_la.iloc[1:].reset_index(drop=True)
fuel_poverty_la.head()

,Local Authority code,Nation or Region,County or Unitary Authority,Local Authority District,Number of households,Number of households in fuel poverty,Proportion of households fuel poor (%)
0,E92000001,ENGLAND,NaN,NaN,24568372,2801647,11.4
1,E12000001,NORTH EAST,NaN,NaN,1217443,129082,10.6
2,E06000047,NORTH EAST,County Durham,NaN,242909,27698,11.4
3,E06000005,NORTH EAST,Darlington,NaN,50630,5482,10.83
4,E06000001,NORTH EAST,Hartlepool,NaN,42412,4496,10.6

In [24]:
fuel_poverty_la_cd = fuel_poverty_la[
    fuel_poverty_la["Local Authority code"] == LA_CODE
].copy()

fuel_poverty_la_cd

,Local Authority code,Nation or Region,County or Unitary Authority,Local Authority District,Number of households,Number of households in fuel poverty,Proportion of households fuel poor (%)
2,E06000047,NORTH EAST,County Durham,NaN,242909,27698,11.4

In [26]:
postcode_join = epc_postcode.copy()
postcode_join["la_fuel_poverty_pct"] = float(
    fuel_poverty_la_cd["Proportion of households fuel poor (%)"].iloc[0]
)
postcode_join.head()

,postcode,properties,share_low_rating,share_low_efficiency,avg_current_efficiency,avg_potential_efficiency,avg_improvement_gap,risk_score,risk_band,la_fuel_poverty_pct
0,DH1 1AF,35,0.114286,0.114286,64.600000,79.371429,14.771429,0.141080,High,11.4
1,DH1 1AH,31,0.129032,0.129032,63.000000,78.709677,15.709677,0.156031,High,11.4
2,DH1 1AL,31,0.096774,0.096774,63.516129,79.838710,16.322581,0.132285,High,11.4
3,DH1 1AQ,22,0.181818,0.181818,61.318182,79.636364,18.318182,0.207028,Very High,11.4
4,DH1 1AS,36,0.166667,0.166667,62.222222,82.666667,20.444444,0.202054,High,11.4

In [28]:
join_file = RAW_PATH / f"postcode_epc_fuelpoverty_{LA_CODE}.csv"
postcode_join.to_csv(join_file, index=False)
print("Saved:", join_file)

Saved: C:\Users\swapn\OneDrive\Desktop\fuel_poverty_risk_england\data\raw\postcode_epc_fuelpoverty_E06000047.csv